# Generated by Django 5.2 on 2025-04-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دوره')),
                ('teacher_name', models.CharField(max_length=40, verbose_name='نام مدرس')),
                ('teacher_family', models.CharField(max_length=50, verbose_name='نام خانوادگی مدرس')),
                ('teacher_licence', models.CharField(max_length=30, verbose_name='مدرک مدرس')),
                ('desciption', models.TextField(verbose_name='توضیحات')),
                ('number_of_sessions', models.IntegerField(verbose_name='تعداد جلسات')),
                ('price', models.IntegerField(verbose_name='شهریه')),
                ('group', models.CharField(choices=[('1', 'all'), ('2', 'office'), ('3', 'graphic'), ('4', 'web design'), ('5', 'engineering')], max_length=2, verbose_name='دسته')),
            ],
        ),
        migrations.CreateModel(
            name='LearningWorkshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(max_length=50, verbose_name='نام کارگاه')),
                ('teacher_name', models.CharField(max_length=40, verbose_name='نام مدرس')),
                ('teacher_family', models.CharField(max_length=50, verbose_name='نام خانوادگی مدرس')),
                ('teacher_licence', models.CharField(max_length=30, verbose_name='مدرک مدرس')),
                ('people', models.CharField(max_length=10, verbose_name='مخاطبین')),
                ('workshop_price', models.IntegerField(verbose_name='شهریه')),
            ],
        ),
    ]
